cropping: true
color_dist_thresh: 20.0
color_filter: false
downsampling: false
downsampling_leaf_size: 0.01
keep_organized: false
limit_xmax: 0.5
limit_xmin: -0.5
limit_ymax: 0.5
limit_ymin: -0.5
limit_zmax: 1.5
limit_zmin: 0.3
publish_limits: true
segmenting: false
plane_tolerance: 0.005
outliers_filter: false
outliers_mean_k: 50
outliers_std_mul: 2.0
estimator: {
    spawn: false,
    cluster_tol: 0.05,
    iterations: 5,
    neighbors: 20,
    object_calibration: false,
    always_success: true,
    rmse_thresh: 0.005,
    broadcast_tf: true,
    publish_markers: true
    }
listener: {
    spawn: false,
    listen_right_arm: false,
    listen_right_hand: false,
    listen_left_arm: false,
    listen_left_hand: false,
    remove_right_arm: false,
    remove_right_hand: false,
    remove_left_arm: false,
    remove_left_hand: false,
    geometry_scale: 1.1,
    publish_markers: true
    }
sensor: {
    internal: false,
    broadcast_identity_tf: false,
    name: "kinect2_optical_frame",
    topic: "/camera/depth_registered/points"
    }
tracker: {
    spawn: false,
    publish_bounding_box: true,
    publish_markers: true,
    broadcast_tf: true
}
in_hand_modeler: {
    spawn: false,
    model_ds_leaf: 0.003,
    normals_ang_thresh: 10.0,
    use_gicp: false
}
