color_dist_thresh: 20.0
color_filter: false
cropping: true
cropping_ref_frame: /qb_delta_base
downsampling: false
downsampling_leaf_size: 0.01
estimator: {always_success: true, broadcast_tf: true, cluster_tol: 0.05, iterations: 5,
  neighbors: 20, object_calibration: false, publish_markers: true, rmse_thresh: 0.005,
  spawn: false}
in_hand_modeler: {model_ds_leaf: 0.003, normals_ang_thresh: 10.0, spawn: false, use_gicp: false}
invert_color_filter: false
keep_organized: false
limit_xmax: 0.27
limit_xmin: -0.27
limit_ymax: 0.35
limit_ymin: -0.02
limit_zmax: 0.762
limit_zmin: 0.6
listener: {geometry_scale: 1.1, listen_left_arm: false, listen_left_hand: false, listen_right_arm: false,
  listen_right_hand: false, publish_markers: true, remove_left_arm: false, remove_left_hand: false,
  remove_right_arm: false, remove_right_hand: false, spawn: false}
outliers_filter: false
outliers_mean_k: 50
outliers_std_mul: 2.0
plane_tolerance: 0.025
publish_limits: true
segmenting: false
sensor: {broadcast_identity_tf: false, internal: false, name: kinect2_optical_frame,
  topic: /camera/depth_registered/points}
tracker: {broadcast_tf: true, publish_bounding_box: true, publish_markers: true, spawn: false}
