cropping: true
downsampling: true
downsampling_leaf_size: 0.005
estimator: {always_success: true, broadcast_tf: true, cluster_tol: 0.05, iterations: 5,
  neighbors: 20, object_calibration: false, publish_markers: true, rmse_thresh: 0.005,
  spawn: false}
keep_organized: false
limit_xmax: 0.2
limit_xmin: -0.10000000000000003
limit_ymax: 0.5
limit_ymin: -0.4
limit_zmax: 0.7
limit_zmin: 0.3
listener: {geometry_scale: 1.1, listen_left_arm: false, listen_left_hand: false, listen_right_arm: false,
  listen_right_hand: false, publish_markers: true, remove_left_arm: false, remove_left_hand: false,
  remove_right_arm: false, remove_right_hand: false, spawn: false}
modeler: {spawn: true, use_color_filtering: true, color_std_dev_multiplier: 1.5}
plane_tolerance: 0.005
publish_limits: true
segmenting: true
sensor: {broadcast_identity_tf: false, internal: false, name: kinect2_optical_frame,
  topic: /camera/depth_registered/points}
tracker: {broadcast_tf: true, publish_bounding_box: true, publish_markers: true, spawn: false}
